### ISSUE TITLE
out folder not created back after delete

### ISSUE THREAD

**Issue by longmaxx** [AlexanderGubarev/RecordVideo-TestComplete-extension#13]
1. build extension
2. build it again
 we have error build.js(19, 1) Microsoft JScript runtime error: Permission denied
in cmd output

**Comment by AlexanderGubarev** [comment]
Waiting after deleting
https://github.com/AlexanderGubarev/RecordVideo-TestComplete-extension/commit/12fbfcf1d5d4937ffb7ec9548e284931172601ba#diff-efd59cd1bdc5c9ac6d0eaa368f1e149f
