### ISSUE TITLE
Incorrect processing of VideoRecorder.Start(Sys)

### ISSUE THREAD

**Issue by DenisPincher** [AlexanderGubarev/RecordVideo-TestComplete-extension#15]
Run _VideoRecorder.Start(Sys)_

Get errors:

`---------------------------
TestComplete
---------------------------
'undefined' is null or not an object

Microsoft JScript runtime error

script.sj  Line: 98  Column: 4.

Plug-in: VideoRecorder 1.0 by SmartBear Software
Location: c:\program files (x86)\smartbear\testcomplete 12\Bin\Extensions\ScriptExtensions\RecordVideo.tcx
---------------------------
OK   Help   
---------------------------

---------------------------
TestComplete
---------------------------
JavaScript runtime error.

Error: 0x80020101

Error location:
Unit: "TestProject210\TestProject210\Script\Unit1"
Line: 25 Column: 17.
---------------------------
OK   
---------------------------`

**Comment by AlexanderGubarev** [comment]
Now, all the types except "string" will be detected and recording will be with Normal quality

**Comment by AlexanderGubarev** [comment]
I'm agree that it'll be good to have such option, but for Help button, not for VideoQuality parameter:
https://github.com/AlexanderGubarev/RecordVideo-TestComplete-extension/issues/10
