### ISSUE TITLE
Log is undefined error on typing "VideoRecorder.Start("Low")."

### ISSUE THREAD

**Issue by DenisPincher** [AlexanderGubarev/RecordVideo-TestComplete-extension#17]
Type:
`VideoRecorder.Start("Low").`

Get error 

> ---------------------------
TestComplete
---------------------------
'Log' is undefined

Microsoft JScript runtime error

script.sj  Line: 124  Column: 4.

Plug-in: VideoRecorder 1.0 by SmartBear Software
Location: c:\program files (x86)\smartbear\testcomplete 12\Bin\Extensions\ScriptExtensions\RecordVideo.tcx
---------------------------
OK   Help   
---------------------------

Top right part of TestComplete (Indicator Area) becomes white afterwards

**Comment by AlexanderGubarev** [comment]
https://smartbear.atlassian.net/browse/TC-72081

**Comment by AlexanderGubarev** [comment]
Fixed by checking if it's on run-time or not
