### ISSUE TITLE
KeywordTests: Design-time user form for Start Video Recording must be implemented

### ISSUE THREAD

**Issue by DenisPincher** [AlexanderGubarev/RecordVideo-TestComplete-extension#18]
Start Video Recording operation must have Quality parameter (Low, Normal, High).
In this case it must have design-time user form with some List control (see the Log Attributes operation implementation).
Otherwise it is not an analogue for the `VideoRecorder.Start(quality)` call.

**Comment by AlexanderGubarev** [comment]
It's decision of @terekhovm and me not to show this form to simplify user process

**Comment by AlexanderGubarev** [comment]
I'm agree that it'll be good to have such option, but for Help button, not for VideoQuality parameter:
https://github.com/AlexanderGubarev/RecordVideo-TestComplete-extension/issues/10

**Comment by terekhovm-pvt** [comment]
I think it is enough for first version to have KDT operation without specifying quality.
