### ISSUE TITLE
Error "'recording Engine' is undefined" when  add 'Start recording' KDT operation

### ISSUE THREAD

**Issue by longmaxx** [AlexanderGubarev/RecordVideo-TestComplete-extension#4]
Error "'recording Engine' is undefined" occurs when  add 'Start recording' KDT operation

![image](https://user-images.githubusercontent.com/11839300/33872302-5da979f8-df27-11e7-8574-d3c1f1c31493.png)

**Comment by longmaxx** [comment]
And then error
![image](https://user-images.githubusercontent.com/11839300/33872367-a6da3a7c-df27-11e7-890e-c1b49253f79e.png)

**Comment by terekhovm-pvt** [comment]
Done
