### ISSUE TITLE
Methods of the VideoRecorder object are not visible in CodeCompletion

### ISSUE THREAD

**Issue by longmaxx** [AlexanderGubarev/RecordVideo-TestComplete-extension#5]
Methods of the VideoRecorder object are not visible in CodeCompletion

**Comment by AlexanderGubarev** [comment]
https://github.com/AlexanderGubarev/RecordVideo-TestComplete-extension/commit/370d24337b1e8359486eacbd1105da30450388d4#diff-e44e4641650f88a85a45790d28fa575f
