### ISSUE TITLE
Look like Quality setting doesn't work

### ISSUE THREAD

**Issue by longmaxx** [AlexanderGubarev/RecordVideo-TestComplete-extension#7]
All at the same time:

In script I set "Low" quality.
In log TC reported "Normal" quality is used.
In VLC output I see "High" quality profile used.

![image](https://user-images.githubusercontent.com/11839300/33873250-55df9e06-df2b-11e7-94d0-2162e5d6c4b3.png)

**Comment by terekhovm-pvt** [comment]
Done
