### ISSUE TITLE
Recording doesn't stop automatically on Stop test

### ISSUE THREAD

**Issue by longmaxx** [AlexanderGubarev/RecordVideo-TestComplete-extension#9]
Run script. Recording won't stop automatically.
function Test()
{
  VideoRecorder.Start()
  Delay(3000)
}

**Comment by AlexanderGubarev** [comment]
Not it's a limitation of script extension engine.
I've added more info about workarounds with TestCompleteEvents:
https://github.com/AlexanderGubarev/RecordVideo-TestComplete-extension/commit/e790d001d8cb89a24009504dbc1af46166673518#diff-04c6e90faac2675aa89e2176d2eec7d8
